# fly.toml app configuration file
app = "okshouse-backend"
primary_region = "nrt"  # Tokyo region

[build]
  dockerfile = "Dockerfile"

[env]
  HOST = "0.0.0.0"
  PORT = "8000"
  ENVIRONMENT = "production"
  DEBUG = "false"
  HTTPS_ONLY = "true"
  SECURE_COOKIES = "true"
  ENABLE_HEALTH_CHECK = "true"
  DATABASE_URL = "sqlite:////data/reservations.db"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = false
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/api/v1/public/health"

[mounts]
  source = "okshouse_data"
  destination = "/data"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512